version: '3.8'
services:
  spring-app:
    build: .
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/codeeditor?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abdawadeen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
